# Generated by Django 3.2 on 2021-05-15 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='aboutus', max_length=300)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default='noimage.jpg', upload_to='benifits')),
            ],
        ),
        migrations.CreateModel(
            name='benifits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default='noimage.jpg', upload_to='benifits')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Noname', max_length=100)),
                ('description', models.TextField(default='description')),
                ('url_slug', models.SlugField(max_length=400, null=True)),
                ('image', models.ImageField(default='noimage.jpg', upload_to='category')),
                ('keyword', models.TextField(default='rootmed')),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='aboutus', max_length=300)),
                ('message', models.TextField(default='')),
                ('email', models.CharField(default='', max_length=400)),
                ('phone', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='main_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='noName', max_length=100)),
                ('description', models.TextField(default='description')),
                ('url_slug', models.SlugField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Noname', max_length=100)),
                ('description', models.TextField(default='description')),
                ('url_slug', models.SlugField(max_length=400, null=True)),
                ('image', models.ImageField(default='noimage.jpg', upload_to='offers')),
                ('keyword', models.TextField(default='rootmed')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='noproduct', max_length=200)),
                ('description', models.TextField(default='noDesciption')),
                ('stock', models.BooleanField(default=True)),
                ('brandname', models.CharField(default='nobrandname', max_length=200)),
                ('actual_price', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('url_slug', models.SlugField(max_length=400, null=True)),
                ('keyword', models.TextField(default='rootmed')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.category')),
            ],
        ),
        migrations.CreateModel(
            name='site_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='MADSL', max_length=100)),
                ('description', models.TextField()),
                ('info1', models.TextField()),
                ('info2', models.TextField()),
                ('address', models.CharField(default='', max_length=400)),
                ('email', models.EmailField(default='support@gmail.com', max_length=400)),
                ('admin_email', models.EmailField(default='support@gmail', max_length=400)),
                ('image', models.ImageField(default='noimage.jpg', upload_to='siteinfo')),
                ('mobile', models.CharField(default='0000000', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('button_name', models.CharField(default='', max_length=80)),
                ('image', models.ImageField(default='noimage.jpg', upload_to='slider')),
                ('url_name', models.URLField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='terms_and_conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(default='', max_length=400)),
                ('condition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(default='Nostore', max_length=400)),
                ('license', models.CharField(default='Nolicense', max_length=400)),
                ('city', models.CharField(default='NOcity', max_length=200)),
                ('state', models.CharField(default='NoStore', max_length=200)),
                ('zipcode', models.CharField(default='NoZipcode', max_length=200)),
                ('address', models.CharField(default='noAddress', max_length=320)),
                ('is_verified', models.BooleanField(default=False)),
                ('summery', models.TextField(default='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='side_effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Noeffect', max_length=200)),
                ('summery', models.TextField(default='Nosummery')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.product')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=1)),
                ('comment', models.TextField(default='Nocomment')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(default='NoQuestion', max_length=100)),
                ('answer', models.TextField(default='NoAnswer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.product')),
            ],
        ),
        migrations.CreateModel(
            name='offers_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.offers')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.product')),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='product')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.product')),
            ],
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='noName', max_length=100)),
                ('description', models.TextField(default='noDesciption')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.product')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.main_category'),
        ),
        migrations.CreateModel(
            name='available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.product')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.vendor')),
            ],
        ),
    ]
