# Generated by Django 3.2 on 2021-05-27 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_best_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best_category',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.category'),
        ),
    ]
