# Generated by Django 3.2 on 2021-05-18 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='custid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='delivery_charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowerlimit', models.IntegerField(default=0)),
                ('upperlimit', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=400)),
                ('tex', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='emailnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='suppot@email.com', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=60)),
                ('location', models.CharField(default='', max_length=400)),
                ('zipcode', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=400)),
                ('mobile', models.CharField(default='', max_length=22)),
                ('notes', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now=True)),
                ('tolal_tax', models.IntegerField(default=0)),
                ('tolal_item_price', models.IntegerField(default=0)),
                ('delivery_charge', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('mode', models.CharField(default='cod', max_length=60)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('is_verify', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='remember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('custid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prico.custid')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cms.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prc1', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='prc')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prico.order')),
            ],
        ),
        migrations.CreateModel(
            name='otp_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(default='', max_length=10)),
                ('attempt', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prico.order')),
            ],
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prico.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.product')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=400)),
                ('content', models.TextField()),
                ('link', models.URLField()),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='forget_password_otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(default='', max_length=10)),
                ('attempt', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('custid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prico.custid')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cms.product')),
            ],
        ),
    ]
