# Generated by Django 3.2 on 2021-05-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prico', '0003_auto_20210526_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='district',
            new_name='city',
        ),
    ]
